source 'https://github.com/CocoaPods/Specs'
source "https://github.com/TouchInstinct/Podspecs.git"

platform :ios, '<%= deployment_target %>'

use_frameworks!
inhibit_all_warnings!

project '<%= project_name %>', {
    'StandardDebug' => :debug,
    'EnterpriseDebug' => :debug,
    'StandardRelease' => :release,
    'EnterpriseRelease' => :release
}

target '<%= project_name %>' do
  pod 'LeadKit'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SwiftLint'
end

# If you have slow HDD
ENV['COCOAPODS_DISABLE_STATS'] = "true"
